# /etc/systemd/system/getty@tty1.service.d/autologin.conf
# 
# Override default getty service to autologin as root
[Service]
ExecStart=
ExecStart=-/sbin/agetty --noreset --noclear --autologin root - ${TERM}
ConditionPathExists=/run/initramfs/live