name: Build bootc images
permissions:
  contents: read
  packages: write
  id-token: write
on:
  schedule:
    - cron: "0 4 * * *" # every day at 4am UTC
  workflow_dispatch:
  push:

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        variant:
          - name: nothing
            image: ghcr.io/ultramarine-linux/shade/nothing
          # - name: cinnamon
          #   image: ghcr.io/ultramarine-linux/shade/cinnamon:${{ github.ref_name || 'main' }}
          # - name: sway
          #   image: ghcr.io/ultramarine-linux/shade/sway:${{ github.ref_name || 'main' }}
    uses: ./.github/workflows/reusable-build-variant.yaml
    with:
      variant_name: ${{ matrix.variant.name }}
      variant_image: ${{ matrix.variant.image }}
      cache_tag: ${{ env.CACHE_TAG }}
    secrets: inherit
