# SPDX-FileCopyrightText: 2025 Cappy Ishihara <@cappy@fyralabs.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Build bootc images
permissions:
  contents: read
  packages: write
  id-token: write
on:
  schedule:
    - cron: "0 4 * * *" # every day at 4am UTC
  workflow_dispatch:
  push:

jobs:
  # temporarily disable to test iso builds faster
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        variant: # add new shade variants here
          - name: nothing
            image: ghcr.io/ultramarine-linux/shade/nothing
          # - name: cinnamon
          #   image: ghcr.io/ultramarine-linux/shade/cinnamon
          # - name: sway
          #   image: ghcr.io/ultramarine-linux/shade/sway
    uses: ./.github/workflows/reusable-build-variant.yaml
    with:
      variant_name: ${{ matrix.variant.name }}
      variant_image: ${{ matrix.variant.image }}
    secrets: inherit

  iso:
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        variant: # add new shade variants here
          - name: nothing
            image: ghcr.io/ultramarine-linux/shade/nothing
          # - name: cinnamon
          #   image: ghcr.io/ultramarine-linux/shade/cinnamon
          # - name: sway
          #   image: ghcr.io/ultramarine-linux/shade/sway
    needs: build # wait for build job to complete before running iso job
    uses: ./.github/workflows/build-iso.yaml
    with:
      variant_name: ${{ matrix.variant.name }}
      variant_image: ${{ matrix.variant.image }}
      image_tag: ${{ needs.build.outputs.image_tag }}
    secrets: inherit
